const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";
export {
  USER_REGISTRATION_REQUEST,
  USER_REGISTRATION_SUCCESS,
  USER_REGISTRATION_FAIL,
};
